openapi: 3.1.0

info:
  title: 端末間メモ共有アプリ
  summary: WEBブラウザで使用することができ，端末間でメモを共有することができるアプリケーションです． 
  version: 1.0.0

paths:
  /memos/:
    post:
      tags: [メモ]
      summary: メモを取得する
      description: メモを取得するエンドポイント
      requestBody:
        description: passkeyを含めてください
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/passkeyRequest'
        required: true
      responses:
        '200':
          description: メモの取得に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memoResponse'
        '400':
          description: パスキーがリクエストボディに含まれていない
          content:
            application/json:
              example:
                detail: passkeyをリクエストボディに含めてください．
        '404':
          description: メモが見つからない
          content:
            application/json:
              example:
                detail: No Memo matches the given query.
  /memos/{memoId}/:
    get:
      tags: [メモ]
      summary: メモをmemoIdを用いて取得する
      description: メモをmemoIdを用いて取得するエンドポイント
      parameters:
        - name: memoId
          in: path
          required: true
          description: メモのID
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: メモの取得に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memoResponse'
        404:
          description: 当該メモが存在しない
          content:
            application/json:
              example:
                detail: No Memo matches the given query.
    delete:
      tags: [メモ]
      summary: 対象のメモを削除する
      description: 対象のメモを削除するエンドポイント
      parameters:
        - name: memoId
          in: path
          required: true
          description: メモのID
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: メモの削除に成功
          content:
            application/json:
              example:
                detail: メモを削除しました．
        404:
          description: 当該メモが存在しない
          content:
            application/json:
              example:
                detail: No Memo matches the given query.
  /memos/create/:
    post:
      tags: [メモ]
      summary: メモを作成する
      description: メモを作成するエンドポイント
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/memoRequest'
        required: true
      responses:
        '201':
          description: メモの作成に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memoResponse'
        400:
          description: メモが空欄
          content:
            application/json:
              example:
                memo:
                  - この項目は空にできません。
  /memos/delete_expired_memos/:
    post:
      tags: [メモ]
      summary: 期限切れのメモを削除する
      description: 作成から一定時間経過したメモを削除するエンドポイント
      responses:
        '200':
          description: 期限切れのメモの削除に成功
          content:
            application/json:
              example:
                detail: 4個のmemoを削除しました．


components:
  schemas:
    id:
      type: string
      format: uuid
      examples:
        - 90dd991f-c7d6-4130-8bf9-f14d42afea51
    memo:
      type: string
      examples:
        - あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。
    passkey:
      type: string
      examples:
        - t40ab9
    created_at:
      type: string
      format: date-time
      examples:
        - 2024-09-16T10:35:49.716241+09:00

    memoResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
        memo:
          $ref: '#/components/schemas/memo'
        passkey:
          $ref: '#/components/schemas/passkey'
        created_at:
          $ref: '#/components/schemas/created_at'
    passkeyRequest:
      type: object
      properties:
        passkey:
          $ref: '#/components/schemas/passkey'
    memoRequest:
      type: object
      properties:
        memo:
          $ref: '#/components/schemas/memo'
