# Generated by Django 4.2.16 on 2024-12-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memo",
            name="qr_img",
        ),
    ]
